server.modules = (
  "mod_cgi",
  "mod_setenv",
  "mod_rewrite",
  "mod_redirect",
)

server.document-root = "/www"
server.errorlog      = "/dev/stderr"
server.pid-file      = "/run/lighttpd.pid"
server.port          = 8088

index-file.names = ( "index.html" )

mimetype.assign = (
  ".html"  => "text/html",
  ".js"    => "application/javascript",
  ".css"   => "text/css",
  ".json"  => "application/json",
  ".svg"   => "image/svg+xml",
  ".png"   => "image/png",
  ".ico"   => "image/x-icon",
  ".woff2" => "font/woff2",
  ".webmanifest" => "application/manifest+json",
)

include "conf.d/80-nfqws.conf"
